shader_type spatial;

uniform sampler2D albedo_texture: source_color, hint_default_white;

uniform float wireframe_width_min = 10.0;
uniform float wireframe_width_max = 20.0;
uniform float wireframe_scale = 200.0;
uniform float wireframe_pow = 2.71;

varying float fragment_distance;


float barycentric_wireframe(vec4 vertex_color) {
	vec3 coordinates = vertex_color.rgb;
	int mode = int((1.0 - vertex_color.a) * 16.0);
	vec3 icoordinates = vec3(1.0) - vertex_color.rgb;
	vec3 scale = fragment_distance / fwidth(coordinates);

	/* blending between absolute and relative wireframe width */
	float c = max(max(vertex_color.r, vertex_color.g), vertex_color.b);
	float blend = pow(2.0 * clamp(c - 0.5, 0.0, 0.5), wireframe_pow);
	scale = mix(scale, vec3(wireframe_scale), blend);

	bool r_flag = bool(mode & 1);
	bool g_flag = bool(mode & 2);
	bool b_flag = bool(mode & 4);
	bool n_flag = bool(mode & 8);

	float mask = wireframe_width_max;
	if (!r_flag) { mask = min(mask, coordinates.r * scale.r); }
	if (!g_flag) { mask = min(mask, coordinates.g * scale.g); }
	if (!b_flag) { mask = min(mask, coordinates.b * scale.b); }

	float imask = wireframe_width_max;
	if (!(r_flag && g_flag && b_flag)) {
		if (!n_flag) { imask = min(imask, icoordinates.r * scale.r); }
		imask = min(imask, icoordinates.g * scale.g);
		imask = min(imask, icoordinates.b * scale.b);
	}

	mask = smoothstep(wireframe_width_min, wireframe_width_max, mask);
	imask = smoothstep(wireframe_width_min, wireframe_width_max, imask);
	return min(mask, imask);
}


void vertex() {
	vec3 world_position = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
	fragment_distance = distance(CAMERA_POSITION_WORLD, world_position);
}


void fragment() {
	ALBEDO = vec3(barycentric_wireframe(COLOR));
	ALBEDO *= texture(albedo_texture, UV).rgb;
	METALLIC = 0.0; SPECULAR = 0.0;
}
